<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PositionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('positions')->delete();

        \DB::table('positions')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Coordinador General de Servicios Públicos Municipales',
                'responsable' => 'Alejandro Sotelo Urióstegui',
                'phone' => '7441889692',
                'extension' => '4250',
                'movil' => NULL,
                'email' => NULL,
                'location' => 'Av. Constituyentes',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'DIRECTOR DE SANEAMIENTO BÁSICO',
                'responsable' => 'LIC. PASCUAL DÍAZ LÓPEZ',
                'phone' => '744188 866',
                'extension' => '4733, 4728',
                'movil' => '7445074457',
                'email' => 'raullopezsv@gmail.com',
                'location' => 'CALLE JUAN N ALVAREZ CIUDAD RENACIMIENTO S/N. ATRAS DE LA MULTIPLAZA DEL CARACOL',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 21:14:54',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'DIRECTOR DE ALUMBRADO PÚBLICO',
                'responsable' => 'ING. ERICK ALBERTO BELLO JAIMES',
                'phone' => '7441894717',
                'extension' => '3120',
                'movil' => '0',
                'email' => 'ebello_jaimes@hotmail.com',
                'location' => 'Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'DIRECTOR DE PANTEONES Y VELATORIOS',
                'responsable' => 'C.P. RAFAEL GARCÍA CIPRIANO ',
                'phone' => '744440 704',
                'extension' => '4205,   42',
                'movil' => '0',
                'email' => 'rafabrisas@gmail.com',
                'location' => 'Donde esta un Restaurante Viejo, a la  izq antes de subir las escaleras de Reglamentos',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'DIRECTOR DE ÁREAS VERDES',
                'responsable' => 'LIC. MIGUEL ÁNGEL HERNÁNDEZ GALEANA',
                'phone' => '',
                'extension' => '4733, 4728',
                'movil' => '0',
                'email' => 'angelhg88@gmail.com',
                'location' => 'Ex Zona',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'DIRECTOR DE IMAGEN URBANA',
                'responsable' => 'LIC. RUFINO CARRILLO PÉREZ',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'rufinocarrilloperez87@gmail.com',
                'location' => 'Ex Zona',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'DIRECTOR DE MERCADOS Y CENTRALES DE ABASTO',
                'responsable' => 'C. MARIO ARTURO CASTILLO RAMOS',
                'phone' => '7444822589',
                'extension' => '',
                'movil' => '0',
                'email' => 'mario.subetealcambio@gmail.com',
                'location' => 'Mercado Central',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'DIRECTOR DE CONSERVACIÓN Y MANTENIMIENTO ',
                'responsable' => 'LIC. GUALBERTO MÉNDEZ BAUTISTA',
                'phone' => '7444832200',
                'extension' => '',
                'movil' => '0',
                'email' => 'gualberto_mendez@hotmail.com',
                'location' => 'Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'DIRECTOR DE RASTROS',
                'responsable' => 'C. JOSÉ LUIS ROJAS PAREDES',
                'phone' => '7443007306',
                'extension' => '',
                'movil' => '0',
                'email' => 'picho_rojas@hotmail.com',
                'location' => 'Ex Zona',
                'contactable' => 'No',
                'area_id' => 2,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Secretaria de Desarrollo Social',
                'responsable' => 'M.C. Leticia Lozano Zavala',
                'phone' => '440 7051',
                'extension' => '6521',
                'movil' => NULL,
                'email' => 'lety_lozano_@hotmail.com',
                'location' => 'Palacio Federal, 2do piso',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'SUBSECRETARIO DE DESARROLLO HUMANO',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Edificio atrás de Soriana Cuauhtémoc, donde era Movimiento Ciudadano',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'DIRECTOR DE FOMENTO EDUCATIVO',
                'responsable' => 'LIC. EDWIN BAUTISTA BALLESTEROS',
                'phone' => '7441906615',
                'extension' => '',
                'movil' => '0',
                'email' => 'e.bautista_07@hotmail.com',
                'location' => 'Edificio Oviedo, Segundo Piso, Depto. 9',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'DIRECTORA DE PREVENCIÓN Y ATENCIÓN A LA VIOLENCIA INTRAFAMILIAR',
                'responsable' => '',
                'phone' => '7444824717',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Capitan Mala Espina No. 2 Fracc Hornos',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'DIRECTOR MUNICIPAL DE CULTURA',
                'responsable' => 'LIC. MANUEL SALVADOR MACIEL CAMPOS',
                'phone' => '7444866836',
                'extension' => '',
                'movil' => '0',
                'email' => 'maciel2165@yahoo.com.mx',
                'location' => 'Calle Malaspina entrando por la calle que está junto al Novedades antes de llegar a Sears por atrás, hay una Bugambilia',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'DIRECTOR DE LA ESCUELA DE INICIACIÓN ARTÍSTICA DE ACAPULCO G65',
                'responsable' => 'LIC. ILIAN NEFTALI BLANCO SÁNCHEZ',
                'phone' => '7444800592',
                'extension' => '',
                'movil' => '0',
                'email' => 'soyilianblanco@gmail.com',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'SUBSECRETARIO DE NORMATIVIDAD Y PROYECTOS ESPECIALES',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Ex Zona',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'DIRECTOR DE DESARROLLO SUSTENTABLE',
                'responsable' => 'ARQ. MARTÍN ZURIEL HERNÁNDEZ ÁLVAREZ ',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'martin-2ha@hotmail.com',
                'location' => 'ex zona',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'DIRECTORA DE PROMOCIÓN Y DIFUSIÓN ',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Ex Zona',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'SUBSECRETARIO DE POLÍTICAS SOCIALES',
                'responsable' => '',
                'phone' => '7444407000',
                'extension' => '6525',
                'movil' => '0',
                'email' => '',
                'location' => 'Palacio Federal, 2do piso',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'DIRECTOR DE PROMOCIÓN  Y RECREACIÓN DEPORTIVA',
                'responsable' => 'C. DAVID GASPAR HERNÁNDEZ',
                'phone' => '7444858851',
                'extension' => '',
                'movil' => '0',
                'email' => 'davidgasparhdz@gmail.com',
                'location' => 'Unidad Deportiva Vicente Suárez',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'DIRECTORA DE ATENCIÓN A GRUPOS VULNERABLES Y MIGRANTES',
                'responsable' => 'MTRA. FRANCIA CRISTINA RAMÍREZ ESTRADA',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'intogracesomosiguales@hotmail.com',
                'location' => 'Auditorio Parque Papagayo, donde era el GYM',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'DIRECTOR DE PROVISIÓN POPULAR',
                'responsable' => 'C.P. ETANISLAO VITAL RADILLA',
                'phone' => '7443607706',
                'extension' => '',
                'movil' => '0',
                'email' => 'tanivital042@hotmail.com',
                'location' => 'Edifico Oviedo Primer piso, oficina 25',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'DIRECTORA DE ATENCIÓN A GRUPOS ÉTNICOS',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Calle Azueta, mismo lugar que IMJUVE',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'DIRECTORA DE PLANEACIÓN Y EVALUACIÓN',
                'responsable' => 'M.C. MÓNICA VIOLETA BONILLA LEÓN',
                'phone' => '7446882164',
                'extension' => '',
                'movil' => '0',
                'email' => 'moni_violet@hotmail.com',
                'location' => 'ex zona',
                'contactable' => 'No',
                'area_id' => 3,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'DIRECTOR GENERAL DE ECOLOGÍA Y PROTECCIÓN AL MEDIO AMBIENTE',
                'responsable' => 'DR. JESÚS CASTILLO AGUIRRE',
                'phone' => '7444866212',
                'extension' => 'jesuscasti',
                'movil' => '0',
                'email' => 'jesuscastillo09@hotmail.com',
            'location' => 'Ex Zona (Calle Hornitos #7, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 4,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'DIRECTOR DE NORMATIVIDAD E IMPACTO AMBIENTAL',
                'responsable' => '',
                'phone' => '7444866212',
                'extension' => '',
                'movil' => '0',
                'email' => '',
            'location' => 'Ex Zona (Calle Hornitos #7, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 4,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'DIRECTOR DE INSPECCIÓN Y VIGILANCIA',
                'responsable' => 'LIC. JOSÉ LUIS VÉLEZ HERNÁNDEZ',
                'phone' => '7444866212',
                'extension' => '',
                'movil' => '0',
                'email' => '',
            'location' => 'Ex Zona (Calle Hornitos #7, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 4,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'DIRECTORA DE EDUCACIÓN Y CULTURA ECOLÓGICA',
                'responsable' => '',
                'phone' => '7444866212',
                'extension' => '',
                'movil' => '0',
                'email' => '',
            'location' => 'Ex Zona (Calle Hornitos #7, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 4,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'SECRETARIA DE DESARROLLO URBANO Y OBRAS PÚBLICAS ',
                'responsable' => 'ING. LUZ MARÍA MERAZA RADILLA',
                'phone' => '7444407093',
                'extension' => '4190, 4295',
                'movil' => '0',
                'email' => 'luzmerazar@hotmail.com',
            'location' => 'Ayuntamiento Viejo (Calle Roberto Posada y Comonfort S/N, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 5,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'DIRECTORA DE DESARROLLO URBANO Y VIVIENDA',
                'responsable' => 'ING. AIDA GUADALUPE LÓPEZ OCHOA',
                'phone' => '7444407093',
                'extension' => '4197, 4175',
                'movil' => '0',
                'email' => 'oaida712@gmail.com',
                'location' => 'Ayuntamiento Viejo',
                'contactable' => 'No',
                'area_id' => 5,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'DIRECTORA DE CARTOGRAFÍA MUNICIPAL',
                'responsable' => '',
                'phone' => '7444407093',
                'extension' => '4242',
                'movil' => '0',
                'email' => '',
                'location' => 'Ayuntamiento Viejo',
                'contactable' => 'No',
                'area_id' => 5,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'DIRECTOR DE OBRAS PÚBLICAS',
                'responsable' => 'ARQ. ALFREDO GARCÍA VÁZQUEZ',
                'phone' => '7444407098',
                'extension' => '4222, 4224',
                'movil' => '0',
                'email' => 'gava_71@hotmail.com',
                'location' => 'Ayuntamiento Viejo',
                'contactable' => 'No',
                'area_id' => 5,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'DIRECTOR DE MAQUINARIA PESADA Y PARQUE VEHICULAR',
                'responsable' => 'C. SILVESTRE GÓMEZ MARTÍNEZ',
                'phone' => '',
                'extension' => '3121',
                'movil' => '0',
                'email' => 'ponchogomezmartinez1985@gmail.com',
                'location' => 'Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 5,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'SECRETARIO DE SEGURIDAD PÚBLICA',
                'responsable' => 'CAP. CORB CG.  MAXIMILIANO SERRANO PÉREZ',
                'phone' => '7444407020',
                'extension' => '3790, 3727',
                'movil' => '0',
                'email' => 'm_serrano_p@hotmail.com',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'DIRECTORA ADMINISTRATIVA DE LA SECRETARIA DE SEGURIDAD PÚBLICA',
                'responsable' => 'C.P. MA. DEL ROCÍO SÁNCHEZ MORA',
                'phone' => '7444407020',
                'extension' => '3732, 3739',
                'movil' => '0',
                'email' => 'rouse.71@hotmail.com',
                'location' => 'Ex zona militar, a un lado de la hemeroteca',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'DIRECTOR DE LA POLICÍA MUNICIPAL URBANA',
                'responsable' => 'C. SAMUEL BUENFIL ESPINOZA',
                'phone' => '',
                'extension' => '3791',
                'movil' => '0',
                'email' => 'samuel09buenfil81@gmail.com',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'DIRECTOR DE LA POLICÍA VIAL',
                'responsable' => 'ALEJANDRO JAVIER ANDALÓN MENDOZA',
                'phone' => '7444407020',
                'extension' => '3793',
                'movil' => '0',
                'email' => '',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            37 =>
            array (
                'id' => 38,
                'name' => ' DIRECTOR DE LA POLICÍA DE PROTECCIÓN Y ASISTENCIA TURÍSTICA',
                'responsable' => 'LIC. SAMUEL ANDREI SOLIS ROJAS',
                'phone' => '7444828852',
                'extension' => '',
                'movil' => '0',
                'email' => 'samuelsoliskalel@gmail.com',
                'location' => 'Modulo de policía en av. Costera frente al cici',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'DIRECTOR DE LA POLICÍA RURAL Y PREVENTIVA',
                'responsable' => 'LIC. ANTONIO JAIMES SALGADO',
                'phone' => '7444407020',
                'extension' => '3735',
                'movil' => '0',
                'email' => 'antoniojasa@hotmail.com',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'DIRECTOR DE LA POLICÍA  AUXILIAR PREVENTIVA',
                'responsable' => 'JESÚS CATALAN MARTÍNEZ',
                'phone' => '7444407023',
                'extension' => '3740',
                'movil' => '0',
                'email' => '',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'DIRECTOR DE LA ACADEMIA DE POLICÍA ',
                'responsable' => 'LIC. EDUARDO CHÁVEZ MANZANAREZ',
                'phone' => '7444407020',
                'extension' => '3709',
                'movil' => '0',
                'email' => 'lalosesentaynueve76@gmail.com',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'ENCARGADO DE DESPACHO DE LA DIRECCIÓN DEL CENTRO DE ATENCIÓN A EMERGENCIAS URBANAS',
                'responsable' => 'ING. DAVID SOTO SOLÍS',
                'phone' => '7444407020',
                'extension' => '3798',
                'movil' => '0',
                'email' => 'ing-davids@hotmail.com',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'UNIDAD ESPECIALIZADA DE LA POLICÍA PARA LA ATENCIÓN DE LA VIOLENCIA FAMILIAR Y DE GÉNERO ',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'SECRETARIA EJECUTIVA DEL CONSEJO MUNICIPAL DE SEGURIDAD PÚBLICA',
                'responsable' => 'LIC. MARTHA PATRICIA LÓPEZ RUIZ',
                'phone' => '7441881547',
                'extension' => '',
                'movil' => '0',
                'email' => 'cmsp.acapulco@gmail.com',
                'location' => 'Cerrada de Caminos S/N, Col. Progreso ',
                'contactable' => 'No',
                'area_id' => 6,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            44 =>
            array (
                'id' => 45,
                'name' => ' COORDINADOR GENERAL DE MOVILIDAD Y TRANSPORTE',
                'responsable' => 'LIC. JOSE RAMIREZ ARREGUIN',
                'phone' => '7444407020',
                'extension' => '3713',
                'movil' => '0',
                'email' => 'jr_arreguin@hotmail.com',
                'location' => 'Calle el Morro costera vieja',
                'contactable' => 'No',
                'area_id' => 7,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'DIRECTOR DE MOVILIDAD VIAL',
                'responsable' => 'LIC. HUGO DE JESÚS MORILLON CISNEROS',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'hugo_morillon@hotmail.com',
                'location' => 'Calle el Morro costera vieja',
                'contactable' => 'No',
                'area_id' => 7,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'DIRECTOR DE TRÁMITES Y REQUERIMIENTOS CIUDADANOS',
                'responsable' => 'ING. PAULINO NICOLÁS GALEANA',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'nicolas310114@gmail.com',
                'location' => 'Calle el Morro costera vieja',
                'contactable' => 'No',
                'area_id' => 7,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'DIRECCION DE EDUCACIÓN DE CULTURA Y MOVILIDAD',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Calle el Morro costera vieja',
                'contactable' => 'No',
                'area_id' => 7,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'SECRETARIO DE PLANEACIÓN Y DESARROLLO ECONÓMICO',
                'responsable' => 'C.P. ERIC ROMERO MORALES',
                'phone' => '7444407008',
                'extension' => '6538',
                'movil' => '0',
                'email' => 'eric.romorales@gmail.com',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'DIRECTOR DEL INSTITUTO MUNICIPAL DE PLANEACIÓN ',
                'responsable' => 'M.C. YAIR SERASER GARCÍA DELGADO',
                'phone' => NULL,
                'extension' => 'no tienen ',
                'movil' => '0',
                'email' => 'yairgade@hotmail.com',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'DIRECTORA DE PLANEACIÓN',
                'responsable' => 'C.P. ROCÍO CLAVEL FABIÁN',
                'phone' => '7444407000',
                'extension' => '6560 6549',
                'movil' => '0',
                'email' => 'rosfab72@hotmail.com',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'ENCARGADA DE DESPACHO DE LA DIRECCIÓN DE PROGRAMACIÓN Y CONTROL PRESUPUESTAL ',
                'responsable' => 'L.C. MARÍA DEL ROCIO GORE MONTALVAN',
                'phone' => '7444407000',
                'extension' => '6613',
                'movil' => '0',
                'email' => 'rociogore@live.com.mx',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'DIRECTORA DE DESARROLLO ECONÓMICO Y ABASTO AGROALIMENTARIO',
                'responsable' => 'LIC. ELIZABETH PARRAS GUTIÉRREZ',
                'phone' => '7444407000',
                'extension' => '6528, 6617',
                'movil' => '0',
                'email' => 'elyparras24@gmail.com',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'DIRECTOR DE DESARROLLO RURAL ',
                'responsable' => 'ING. ÁLVARO DUEÑAS PINEDA',
                'phone' => '7444407000',
                'extension' => '4116',
                'movil' => '0',
                'email' => 'duenaspineda@yahoo.com.mx',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            54 =>
            array (
                'id' => 55,
            'name' => 'DIRECTORA DE FORTALECIMIENTO MUNICIPAL (FORTAMUN)',
                'responsable' => 'C. MARÍA DE LOURDES CRISTINO JAIME',
                'phone' => '7444407000',
                'extension' => '6589, 6590',
                'movil' => '0',
                'email' => 'lourdescristino54@gmail.com',
            'location' => 'Palacio Federal (Av. Costera Miguel Alemán #315, Col. Centro)',
                'contactable' => 'No',
                'area_id' => 8,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'SECRETARIO DE TURISMO MUNICIPAL',
                'responsable' => 'C. DAVID HORACIO ABARCA RODRÍGUEZ',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => 'dabarca.aca@gmail.com',
                'location' => 'Av. Costera Miguel Alemán #123-PB, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'SECRETARIO PARTICULAR',
                'responsable' => 'ANGEL ISAI ARANDA VELÁZQUEZ',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => 'isai.velazquez.aa@outlook.com',
                'location' => 'Av. Costera Miguel Alemán, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'DIRECTOR DE PLANEACIÓN E INNOVACIÓN',
                'responsable' => 'L.A.E.T. ABRAHAM RAMOS GUTIERREZ',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => 'abraham.ramosgutierrez@gmail.com',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'DIRECTORA DE SEGUIMIENTO Y EVALUACIÓN',
                'responsable' => 'ROSARIO CRUZ LÓPEZ',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'DIRECTOR DE VINCULACIÓN Y CONTROL DE FONDOS',
                'responsable' => 'BERNARDA TORRES OLMEDO',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'SUBSECRETARIO DE FOMENTO TURÍSTICO',
                'responsable' => 'ARTURO LÓPEZ SUGIA',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'DIRECTOR DE FOMENTO AL ECOTURISMO',
                'responsable' => 'MTRO. JOSÉ LUIS PELLAT GARCÍA ',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => 'sria.turismo.aca@gmail.com',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'DIRECTOR DE CONVENCIONES Y EVENTOS ESPECIALES',
                'responsable' => '',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            63 =>
            array (
                'id' => 64,
                'name' => ' DIRECTOR DE PROMOCIÓN Y DIFUSIÓN',
                'responsable' => 'GERARDO OCHOA AMORÓS',
                'phone' => '7444859454',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Av. Costera Miguel Alemán #1803, Fracc. Magallanes',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'DIRECTOR DEL CENTRO DE ATENCIÓN Y PROTECCIÓN AL TURISTA ACAPULCO ',
                'responsable' => 'OSCAR ALEJANDRO INSUNZA RAMÍREZ',
                'phone' => '7444849800',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => 'Direccion Av. Costera Miguel Aleman 38-A, altos HSBC frente a Oceanic 2000',
                'contactable' => 'No',
                'area_id' => 9,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            65 =>
            array (
                'id' => 66,
                'name' => 'DIRECTOR GENERAL DE SALUD MUNICIPAL',
                'responsable' => 'DR. ANICETO LEGUIZAMO DIMAS',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'dgsm2124@hotmail.com ',
            'location' => 'Atrás de Soriana Edificio Areli (Vasco Núñez de Balboa #1110 Edificio Areli Col. Hornos Insurgentes C.P. 39550)',
                'contactable' => 'No',
                'area_id' => 10,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            66 =>
            array (
                'id' => 67,
                'name' => 'COORDINADORA DE LOS SERVICIOS DE SALUD',
                'responsable' => 'L.E. LOURDES MENDOZA URIOSTEGUI',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'lulumen16@gmail.com',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 10,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            67 =>
            array (
                'id' => 68,
                'name' => 'DIRECTORA DE SERVICIOS MÉDICOS Y HOSPITALARIOS',
                'responsable' => 'DRA. GUADALUPE BRACHO HERNÁNDEZ',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'areli.rudy14@gmail.com',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 10,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            68 =>
            array (
                'id' => 69,
                'name' => 'DIRECTOR DE SALUD PÚBLICA',
                'responsable' => 'M.B.C. JOSÉ YONATAN FRANCISCO MORALES',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => 'yonatan.fco08@gmail.com',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 10,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            69 =>
            array (
                'id' => 70,
                'name' => 'DIRECTOR DE REGULACIÓN, CONTROL Y FOMENTO SANITARIO',
                'responsable' => 'C. ROGELIO OLGUÍN GONZÁLEZ',
                'phone' => '',
                'extension' => '',
                'movil' => '0',
                'email' => '',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 10,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            70 =>
            array (
                'id' => 71,
                'name' => 'DIRECTORA GENERAL DEL INSTITUTO MUNICIPAL DE LA MUJER',
                'responsable' => 'MTRA. ELIZABETH MAYA PACO',
                'phone' => '7444407185',
                'extension' => '4184',
                'movil' => '',
                'email' => 'immujeracapulco@gmail.com',
                'location' => 'Calle Quebradora Col. Centro, a un costado De La Iglesia, Debajo De Servicios Públicos Municipales',
                'contactable' => 'No',
                'area_id' => 11,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            71 =>
            array (
                'id' => 72,
                'name' => 'DIRECTORA DE INVESTIGACIONES JURÍDICAS DE GÉNERO',
                'responsable' => 'LIC. MARA IRIS SAGUILÁN BIBIANO',
                'phone' => '7444407184',
                'extension' => '4184',
                'movil' => '',
                'email' => 'marairissaguilan27@gmail.com',
                'location' => 'Calle Quebradora Col. Centro, a un costado De La Iglesia, Debajo De Servicios Públicos Municipales',
                'contactable' => 'No',
                'area_id' => 11,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            72 =>
            array (
                'id' => 73,
                'name' => 'DIRECTORA DE CAPACITACIÓN Y DESARROLLO',
                'responsable' => 'MTRA. NORMA EUGENIA MEDINA PITA',
                'phone' => '7444407184',
                'extension' => '4186',
                'movil' => '',
                'email' => '',
                'location' => 'Calle Quebradora Col. Centro, a un costado De La Iglesia, Debajo De Servicios Públicos Municipales',
                'contactable' => 'No',
                'area_id' => 11,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            73 =>
            array (
                'id' => 74,
                'name' => 'DIRECTORA DE PLANEACIÓN, PROMOCIÓN Y ENLACE',
                'responsable' => 'MTRA. ALMA ESLITH RAMÍREZ VALENTE',
                'phone' => '7444881302',
                'extension' => '',
                'movil' => '',
                'email' => 'immujer.planeacion@gmail.com',
            'location' => 'Atrás de Soriana Edificio Areli (Vasco Núñez de Balboa #1110 Edificio Areli Col. Hornos Insurgentes C.P. 39550)',
                'contactable' => 'No',
                'area_id' => 11,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            74 =>
            array (
                'id' => 75,
                'name' => 'DIRECTOR DEL INSTITUTO MUNICIPAL DE LA JUVENTUD',
                'responsable' => 'DR. JESÚS JABETH SALGADO CASARRUBIAS',
                'phone' => '7444802298',
                'extension' => '',
                'movil' => '',
                'email' => '',
                'location' => 'Calle Teniente José Azueta #12 Int. 2 Col. Centro. Por CAPAMA, frente al Hotel María Antonieta',
                'contactable' => 'No',
                'area_id' => 12,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            75 =>
            array (
                'id' => 76,
                'name' => 'PRESIDENTE DEL PATRONATO DEL DIF ACAPULCO',
                'responsable' => 'MTRO. FERNANDO SOLANO RAMIREZ LOPEZ',
                'phone' => '7444831389',
                'extension' => '102',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            76 =>
            array (
                'id' => 77,
                'name' => 'SECRETARIO PARTICULAR DEL PATRONATO',
                'responsable' => '',
                'phone' => '',
                'extension' => '',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            77 =>
            array (
                'id' => 78,
                'name' => 'COORDINADORA DE RELACIONES PÚBLICAS DEL DIF',
                'responsable' => 'LIC. MONICA IVETT NIETO PITA',
                'phone' => '',
                'extension' => '',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            78 =>
            array (
                'id' => 79,
                'name' => 'DIRECTORA GENERAL DEL DIF ACAPULCO',
                'responsable' => 'M.A. ANEL ORDOÑEZ MUÑOZ',
                'phone' => '7444839812',
                'extension' => '131',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            79 =>
            array (
                'id' => 80,
                'name' => 'SECRETARIA PARTICULAR DE LA DIRECCIÓN GENERAL',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '131',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            80 =>
            array (
                'id' => 81,
                'name' => 'SUBDIRECTORA ADMINISTRATIVA',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '106',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            81 =>
            array (
                'id' => 82,
                'name' => 'SUBDIRECTORA DE PLANEACIÓN Y PRESUPUESTO',
                'responsable' => '',
                'phone' => '',
                'extension' => '130',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            82 =>
            array (
                'id' => 83,
                'name' => 'SUBDIRECTOR OPERATIVO',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '108',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            83 =>
            array (
                'id' => 84,
                'name' => 'SUBDIRECTOR DE ASISTENCIA SOCIAL',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '111',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            84 =>
            array (
                'id' => 85,
                'name' => 'SUBDIRECTORA DE BIENESTAR SOCIAL ',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '126',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            85 =>
            array (
                'id' => 86,
                'name' => 'PROCURADOR DE LA DEFENSA DE LAS NIÑAS, NIÑOS Y ADOLESCENTES',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '114',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            86 =>
            array (
                'id' => 87,
                'name' => 'ENCARGADO DE LA CONTRALORÍA GENERAL',
                'responsable' => '',
                'phone' => '7444839812',
                'extension' => '127',
                'movil' => '',
                'email' => '',
                'location' => 'Rio Grande y Mercado s/n, Col. Hogar Moderno',
                'contactable' => 'No',
                'area_id' => 13,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            87 =>
            array (
                'id' => 88,
                'name' => 'ENCARGADO DE DESPACHO  DE LA DIRECCIÓN GENERAL DE LA CAPAMA',
                'responsable' => 'M.C ARTURO LATABAN LÓPEZ',
                'phone' => '7444341402',
                'extension' => '1002',
                'movil' => '',
                'email' => 'arturolataban@gmail.com',
                'location' => 'Av. Lic. Adolfo López Mateos esq. Tte. José Azueta s/n, Col. Centro',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            88 =>
            array (
                'id' => 89,
                'name' => 'DIRECCIÓN JURÍDICA DE LA CAPAMA',
                'responsable' => '',
                'phone' => '7444341400',
                'extension' => '1082',
                'movil' => '',
                'email' => '',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            89 =>
            array (
                'id' => 90,
                'name' => 'DIRECTOR DE OPERACIONES DE LA CAPAMA',
                'responsable' => '485 0902',
                'phone' => '',
                'extension' => '',
                'movil' => '',
                'email' => '',
            'location' => 'Capitán Mala Espina (atrás de SEARS)',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            90 =>
            array (
                'id' => 91,
                'name' => 'CONTRALOR GENERAL DE CAPAMA',
                'responsable' => '',
                'phone' => '7444341400',
                'extension' => '1021',
                'movil' => '',
                'email' => '',
                'location' => 'Av. Lic. Adolfo López Mateos esq. Tte. José Azueta s/n, Col. Centro',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            91 =>
            array (
                'id' => 92,
                'name' => 'DIRECTOR DE FINANZAS DE LA CAPAMA',
                'responsable' => '',
                'phone' => '7444341400',
                'extension' => '1011',
                'movil' => '',
                'email' => '',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            92 =>
            array (
                'id' => 93,
                'name' => 'DIRECTOR COMERCIAL DE LA CAPAMA',
                'responsable' => '',
                'phone' => '7444341400',
                'extension' => '1080',
                'movil' => '',
                'email' => '',
                'location' => '',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            93 =>
            array (
                'id' => 94,
                'name' => 'DIRECTORA DE GESTIÓN CIUDADANA DE LA CAPAMA',
                'responsable' => '',
                'phone' => '7444824713',
                'extension' => '',
                'movil' => '',
                'email' => '',
                'location' => 'Calle fernando siliseo aun costado del rollo, fracc costa azul',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
            94 =>
            array (
                'id' => 95,
                'name' => 'DIRECTOR TÉCNICO DE LA CAPAMA',
                'responsable' => '',
                'phone' => '7444846663',
                'extension' => '',
                'movil' => '',
                'email' => '',
                'location' => 'Calle Fernando siliseo aun costado del rollo, fracc costa azul',
                'contactable' => 'No',
                'area_id' => 14,
                'created_at' => '2022-02-24 22:06:33',
                'updated_at' => '2022-02-24 22:06:49',
            ),
        ));


    }
}
